title: Revista Semillero ECUSTA
copyright: 2021, Semillero Ecusta
author: Semillero Ecusta

execute:
  execute_notebooks: "force"

html:
  use_edit_page_button : true
  use_repository_button: true
  baseurl              : 

repository:
  url: https://github.com/semilleroecusta/research_book
  branch: source

launch_buttons:
  binderhub_url: "https://mybinder.org"
  colab_url    : "https://colab.research.google.com"
  thebe        : true

latex:
  latex_documents:
    targetname: book.tex

parse:
  myst_enable_extensions:
    - html_image
    - dollarmath


bibtex_bibfiles:
  - bibliography.bib

sphinx:
  config:
    bibtex_reference_style: author_year
