title: "(REPLACE WITH Book Title)"
copyright: '(REPLACE WITH Current Year), (REPLACE WITH Author Name)'
author: '(REPLACE WITH Author Name)'

execute:
  execute_notebooks: "force"

html:
  use_edit_page_button : true
  use_repository_button: true
  baseurl              : (REPLACE WITH Project URL)

repository:
  url: (REPLACE WITH Repository URL)
  branch: source

launch_buttons:
  binderhub_url: "https://mybinder.org"
  colab_url    : "https://colab.research.google.com"
  thebe        : true

latex:
  latex_documents:
    targetname: book.tex

parse:
  myst_enable_extensions:
    - html_image
    - dollarmath


bibtex_bibfiles:
  - bibliography.bib

sphinx:
  config:
    bibtex_reference_style: author_year
